// B2: the page rendered from responses captured from the real SQLite-backed
// API. The artifact is generated by tests/test_phase0_frontend_contract.py
// and must not be edited by hand; every test first checks that the state it
// exercises is really present in it.
import React from "react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { act, cleanup, fireEvent, render, screen, within } from "@testing-library/react";

import App from "./App";
import contract from "./test/fixtures/phase0_sqlite_contract.json";

const { responses } = contract;
const UNAVAILABLE_COPY = "Coverage is temporarily unavailable. Please try again shortly.";
const STALE_COPY = /Data may be delayed\./;

function themesFor(ticker) {
  const captured = responses[`themes_${ticker}`];
  expect(captured.status).toBe(200);
  return captured.body;
}

function toResponse({ status, body }) {
  return {
    ok: status >= 200 && status < 300,
    status,
    json: async () => structuredClone(body),
  };
}

// Serves each captured response at the path it was captured from.
// `overrides` maps a path to a captured response or to a function
// returning a promise of one (for deferred delivery).
function serveContract(overrides = {}) {
  const byPath = new Map(
    Object.values(responses)
      .filter((captured) => captured.status === 200)
      .map((captured) => [captured.path, captured]),
  );
  const fetchMock = vi.fn((url) => {
    const path = new URL(url, "http://localhost").pathname;
    const override = overrides[path];
    if (typeof override === "function") return override().then(toResponse);
    const captured = override || byPath.get(path);
    if (!captured) throw new Error(`Unexpected request: ${url}`);
    return Promise.resolve(toResponse(captured));
  });
  vi.stubGlobal("fetch", fetchMock);
  return fetchMock;
}

function requestedPaths(fetchMock) {
  return fetchMock.mock.calls.map(([url]) => new URL(url, "http://localhost").pathname);
}

async function selectTicker(ticker) {
  fireEvent.click(await screen.findByRole("button", { name: new RegExp(`^${ticker} —`) }));
}

async function themeCard(label) {
  return (await screen.findByRole("heading", { level: 3, name: label })).closest("article");
}

function otherCoverageSection() {
  return screen.queryByRole("heading", { level: 2, name: "Other coverage" })?.closest("section") ?? null;
}

afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
});

describe("Ticker Narratives against the real SQLite-backed API contract", () => {
  it("renders a current summary with every citation resolved to its backend story", async () => {
    const tsla = themesFor("TSLA");
    const current = tsla.themes.filter((theme) => !theme.degraded);
    expect(current).toHaveLength(1);
    const [alpha] = current;
    const citedIds = alpha.sentences.flatMap((sentence) => sentence.citation_ids);
    expect(alpha.sentences.some((sentence) => sentence.citation_ids.length > 1)).toBe(true);
    expect(citedIds.some((id) => citedIds.indexOf(id) !== citedIds.lastIndexOf(id))).toBe(true);
    const citationById = new Map(alpha.citations.map((citation) => [citation.id, citation]));

    serveContract();
    render(<App />);

    const card = await themeCard(alpha.label);
    expect(within(card).queryByText(/Summary unavailable/)).not.toBeInTheDocument();
    const paragraphs = card.querySelectorAll(".summary-copy p");
    expect(paragraphs).toHaveLength(alpha.sentences.length);
    alpha.sentences.forEach((sentence, index) => {
      const paragraph = paragraphs[index];
      expect(paragraph.textContent.startsWith(sentence.text)).toBe(true);
      const links = within(paragraph).getAllByRole("link");
      expect(links).toHaveLength(sentence.citation_ids.length);
      links.forEach((link, position) => {
        const citation = citationById.get(sentence.citation_ids[position]);
        expect(citation).toBeDefined();
        expect(link).toHaveAttribute("href", citation.url);
        expect(link).toHaveAttribute("title", `Open source: ${citation.headline}`);
      });
    });
  });

  it("renders a degraded theme with its verbatim M5 label and persisted stories only", async () => {
    const tsla = themesFor("TSLA");
    const [beta] = tsla.themes.filter((theme) => theme.degraded);
    expect(beta.sentences).toEqual([]);
    expect(beta.label.length).toBeGreaterThan(120);
    expect([...beta.label].some((character) => character.codePointAt(0) > 127)).toBe(true);
    const generatedText = tsla.themes.flatMap((theme) => theme.sentences.map((sentence) => sentence.text));
    expect(generatedText.length).toBeGreaterThan(0);

    serveContract();
    render(<App />);

    const card = await themeCard(beta.label);
    expect(within(card).getByRole("heading", { level: 3 }).textContent).toBe(beta.label);
    expect(
      within(card).getByText("Summary unavailable — source stories are still available"),
    ).toBeInTheDocument();
    expect(card.querySelector(".summary-copy")).toBeNull();
    for (const text of generatedText) {
      expect(within(card).queryByText(text, { exact: false })).not.toBeInTheDocument();
    }
    for (const story of beta.stories) {
      expect(within(card).getByRole("link", { name: story.headline })).toHaveAttribute("href", story.url);
    }
  });

  it("renders every Other Coverage story exactly once with its backend link and outlet", async () => {
    const { other_coverage: other } = themesFor("TSLA");
    expect(other.story_count).toBeGreaterThan(0);
    expect(other.stories).toHaveLength(other.story_count);

    serveContract();
    render(<App />);

    await themeCard(themesFor("TSLA").themes[0].label);
    const section = otherCoverageSection();
    expect(section).not.toBeNull();
    expect(within(section).getByText(`Stories (${other.story_count})`)).toBeInTheDocument();
    for (const story of other.stories) {
      expect(screen.getAllByText(story.headline)).toHaveLength(1);
      const link = within(section).getByRole("link", { name: story.headline });
      expect(link).toHaveAttribute("href", story.url);
      expect(link.closest("li")).toHaveTextContent(story.outlet);
    }
  });

  it("shows an M2-only day's live stories as coverage, not as an empty day", async () => {
    const nvda = themesFor("NVDA");
    expect(nvda.themes).toEqual([]);
    expect(nvda.other_coverage.story_count).toBeGreaterThan(0);

    serveContract();
    render(<App />);
    await selectTicker("NVDA");

    const firstStory = nvda.other_coverage.stories[0];
    await screen.findByRole("link", { name: firstStory.headline });
    expect(screen.queryByText("No current coverage for NVDA.")).not.toBeInTheDocument();
    expect(screen.queryByText("Check back after the next update.")).not.toBeInTheDocument();
    expect(screen.queryAllByRole("article")).toHaveLength(0);
    const section = otherCoverageSection();
    expect(section).not.toBeNull();
    for (const story of nvda.other_coverage.stories) {
      expect(within(section).getByRole("link", { name: story.headline })).toHaveAttribute("href", story.url);
    }
  });

  it("shows the empty state for a known ticker with no persisted coverage", async () => {
    const amd = themesFor("AMD");
    expect(amd.themes).toEqual([]);
    expect(amd.other_coverage.story_count).toBe(0);

    serveContract();
    render(<App />);
    await selectTicker("AMD");

    expect(await screen.findByText("No current coverage for AMD.")).toBeInTheDocument();
    expect(screen.getByText("Check back after the next update.")).toBeInTheDocument();
    expect(otherCoverageSection()).toBeNull();
    expect(screen.queryAllByRole("article")).toHaveLength(0);
  });

  it("renders stories whose publication time is null without inventing one", async () => {
    const meta = themesFor("META");
    const [gamma] = meta.themes;
    expect(gamma.degraded).toBe(false);
    const nullStories = [
      ...gamma.stories.filter((story) => story.published_at === null),
      ...meta.other_coverage.stories.filter((story) => story.published_at === null),
    ];
    expect(gamma.stories.some((story) => story.published_at === null)).toBe(true);
    expect(meta.other_coverage.stories.some((story) => story.published_at === null)).toBe(true);

    serveContract();
    render(<App />);
    await selectTicker("META");

    await themeCard(gamma.label);
    await screen.findByRole("link", { name: nullStories[0].headline });
    for (const story of nullStories) {
      expect(screen.getByRole("link", { name: story.headline })).toHaveAttribute("href", story.url);
    }
    expect(document.body.textContent).not.toMatch(/Invalid Date|NaN/);
  });

  it("shows the stale banner for a stale ticker only, not for a fresh one", async () => {
    const tickers = Object.fromEntries(
      responses.tickers.body.tickers.map((ticker) => [ticker.ticker, ticker]),
    );
    expect(responses.meta_status.body.is_stale).toBe(false);
    expect(tickers.TSLA.is_stale).toBe(false);
    expect(tickers.AAPL.is_stale).toBe(true);

    serveContract();
    render(<App />);

    await themeCard(themesFor("TSLA").themes[0].label);
    expect(screen.queryByText(STALE_COPY)).not.toBeInTheDocument();

    await selectTicker("AAPL");
    await themeCard(themesFor("AAPL").themes[0].label);
    expect(screen.getByText(STALE_COPY)).toBeInTheDocument();

    await selectTicker("TSLA");
    await themeCard(themesFor("TSLA").themes[0].label);
    expect(screen.queryByText(STALE_COPY)).not.toBeInTheDocument();
  });

  it("shows the error state and no data when every endpoint returns the real 503", async () => {
    const unavailable = responses.unavailable;
    expect(unavailable.status).toBe(503);
    expect(unavailable.body).toEqual({ detail: "Coverage is temporarily unavailable." });
    const fetchMock = vi.fn(() => Promise.resolve(toResponse(unavailable)));
    vi.stubGlobal("fetch", fetchMock);

    render(<App />);

    expect(await screen.findByText(UNAVAILABLE_COPY)).toBeInTheDocument();
    expect(screen.queryAllByRole("button")).toHaveLength(0);
    expect(screen.queryAllByRole("article")).toHaveLength(0);
    expect(otherCoverageSection()).toBeNull();
    expect(screen.queryByText(/No current coverage/)).not.toBeInTheDocument();
    expect(requestedPaths(fetchMock)).toEqual(
      expect.arrayContaining(["/api/v1/tickers", "/api/v1/meta/status", "/api/v1/tickers/TSLA/themes"]),
    );
  });

  it("scopes a real 503 on one ticker's themes to that ticker", async () => {
    const tsla = themesFor("TSLA");
    serveContract({ "/api/v1/tickers/META/themes": responses.unavailable });
    render(<App />);

    await themeCard(tsla.themes[0].label);
    await selectTicker("META");

    expect(await screen.findByText(UNAVAILABLE_COPY)).toBeInTheDocument();
    expect(screen.queryAllByRole("article")).toHaveLength(0);
    expect(otherCoverageSection()).toBeNull();
    for (const story of tsla.other_coverage.stories) {
      expect(screen.queryByText(story.headline)).not.toBeInTheDocument();
    }

    await selectTicker("TSLA");
    await themeCard(tsla.themes[0].label);
    expect(screen.queryByText(UNAVAILABLE_COPY)).not.toBeInTheDocument();
  });

  it("keeps the newer ticker when an older response arrives late", async () => {
    const tsla = themesFor("TSLA");
    const nvda = themesFor("NVDA");
    let releaseTsla;
    const lateTsla = new Promise((resolve) => {
      releaseTsla = () => resolve(responses.themes_TSLA);
    });
    // The deferred response ignores the abort signal on purpose.
    const fetchMock = serveContract({ "/api/v1/tickers/TSLA/themes": () => lateTsla });
    render(<App />);

    await selectTicker("NVDA");
    await screen.findByRole("link", { name: nvda.other_coverage.stories[0].headline });

    await act(async () => {
      releaseTsla();
      await new Promise((resolve) => setTimeout(resolve, 0));
    });

    expect(screen.getByRole("button", { name: /^NVDA —/ })).toHaveClass("active");
    expect(screen.queryAllByRole("article")).toHaveLength(0);
    for (const theme of tsla.themes) {
      expect(screen.queryByRole("heading", { name: theme.label })).not.toBeInTheDocument();
    }
    for (const story of tsla.other_coverage.stories) {
      expect(screen.queryByText(story.headline)).not.toBeInTheDocument();
    }
    for (const story of nvda.other_coverage.stories) {
      expect(screen.getByRole("link", { name: story.headline })).toBeInTheDocument();
    }
    expect(requestedPaths(fetchMock)).toEqual([
      "/api/v1/tickers",
      "/api/v1/meta/status",
      "/api/v1/tickers/TSLA/themes",
      "/api/v1/tickers/NVDA/themes",
    ]);
  });
});
